<?php
/**
 * @file
 * Contact save module logic.
 */

define('CONTACT_SAVE_MESSAGES_LIST_PATH', 'admin/structure/contact/messages');

require_once 'includes/contact_save.views.inc';

/**
 * Implements hook_menu().
 */
function contact_save_menu() {
  $items['admin/structure/contact/settings'] = array(
    'title' => 'Contact save settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('contact_save_settings'),
    'access arguments' => array('administer contact forms'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
    'file' => 'includes/contact_save.admin.inc',
  );

  $items['admin/structure/contact/message/%/delete'] = array(
    'title' => 'Contact save settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('contact_save_message_delete_form', 4),
    'access arguments' => array('administer contact forms'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/contact_save.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_cron().
 *
 * Deletes old messages.
 */
function contact_save_cron() {
  $live_time = variable_get('contact_save_live_time', 0);
  db_delete('contact_save')
    ->condition('created', REQUEST_TIME - $live_time, '<')
    ->execute();
}

/**
 * Implements hook_mail_alter().
 */
function contact_save_mail_alter(&$message) {
  if ($message['id'] == 'contact_page_mail') {
    $body = $message['body'];
    // Remove default contact string.
    unset($body[0]);
    $record = array(
      'cid' => isset($message['params']['category']['cid']) ? $message['params']['category']['cid'] : 1,
      'uid' => isset($message['params']['sender']) ? $message['params']['sender']->uid : 0,
      'name' => $message['params']['name'],
      'mail' => $message['params']['mail'],
      'subject' => $message['params']['subject'],
      'message' => implode("\n", $body),
      'created' => REQUEST_TIME,
    );

    drupal_write_record('contact_save', $record);
  }
}

/**
 * Implements hook_views_api().
 */
function contact_save_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'contact_save') . '/includes',
  );
}

/**
 * Delete message by ID.
 *
 * @param int $id
 *   Message ID.
 *
 * @return int
 *   Returns 1 if success.
 */
function contact_save_message_delete($id) {
  $query = db_delete('contact_save')
    ->condition('id', $id, '=');

  $result = $query->execute();

  return $result;
}
